package com.xxmrk888ytxx.feature.managementmodule.apprestriction.model

import com.xxmrk888ytxx.core.base.android.mvi.UiState

data class ScreenState(
    val isCameraDisabled: Boolean = false,
    val isMicrophoneDisabled: Boolean = false,
    val isCanDisableUSBDataSignal: Boolean = true,
    val isUSBDataSignalDisabled: Boolean = false,
    val isUSBFileTransferDisabled: Boolean = false,
    val isInstallAppsDisabled: Boolean = false,
    val isInstallAppsFromUnknownSourcesDisabled: Boolean = false,
    val isUninstallAppsDisabled: Boolean = false,
    val isAppControlDisabled: Boolean = false,
    val isCanDisableScreenContentCaptureForAI: Boolean = true,
    val isScreenContentCaptureForAIDisabled: Boolean = false,
    val isContentSuggestionDisabled: Boolean = false,
    val isCanDisableContentSuggestion: Boolean = true,
    val isScreenshotsDisabled: Boolean = false,
    val isDebugFeaturesDisabled: Boolean = false,
    val isFactoryResetDisabled: Boolean = false,
    val isSafeBootDisabled: Boolean = false,
    val isAddUserDisabled: Boolean = false,
    val isRemoveUserDisabled: Boolean = false,
    val isSwitchUserDisabled: Boolean = false,
    val isBluetoothDisabled: Boolean = false,
    val isBluetoothConfigDisabled: Boolean = false,
    val isMountPhysicalMediaDisabled: Boolean = false,
    val isLocationDisabled: Boolean = false,
    val isNFCDisabled: Boolean = false,
    val isCanDisableNFC: Boolean = true,
    val isOutgoingCallsDisabled: Boolean = false,
    val isSMSDisabled: Boolean = false,
    val isWallpaperChangeDisabled: Boolean = false,
    val isFunDisabled: Boolean = false,

    val isWifiStateChangeDisabled: Boolean = false,
    val isWifiConfigDisabled: Boolean = false,
    val isHotspotDisabled: Boolean = false,
    val isAddNewWifiNetworksDisabled: Boolean = false,
    val isAirplaneModeDisabled: Boolean = false,
    val isConfigVPNDisabled: Boolean = false,
    val isConfigPrivateDNSDisabled: Boolean = false,
    val isRoamingDisabled: Boolean = false,
    val isConfigMobileDataDisabled: Boolean = false,
    val is2GNetworkDisabled: Boolean = false,

    val isCanDisableChangeWifiState: Boolean = true,
    val isCanDisableHotspot: Boolean = true,
    val isCanDisableAddNewWifiNetworks: Boolean = true,
    val isCanDisableConfigPrivateDNS: Boolean = true,
    val isCanDisable2GNetwork: Boolean = true,
) : UiState
